GET localhost:8080/material

###

POST localhost:8080/material
Content-Type: application/json

{
  "name": "New Material",
  "url": "https://www.google.pl/",
  "assignmentId": "a1e1f1e1-307f-44d7-a6b8-3fa3ccf1e5ca"
}

###
DELETE localhost:8080/material/a395780e-7642-479f-8aed-3c410ee6b177