GET localhost:8080/task

###

POST localhost:8080/task
Content-Type: application/json

{
  "name": "New Task",
  "isDone": false,
  "assignmentId": "a1e1f1e1-307f-44d7-a6b8-3fa3ccf1e5ca"
}

###
DELETE localhost:8080/task/95441c4a-ece1-4828-9179-006b587ead36